### ISSUE TITLE
Modify to run on FreeBSD

### ISSUE THREAD

**Issue by lamixer** [mythic-beasts/dehydrated-code-rack#1]
Hello! 

I want to restart Postifx and Dovecot after updating certificates, so I found this code. Thank you. Unfortunately it won't run on FreeBSD due to lack of /bin/run-parts.

I'm not much of a programmer, so it's not clear to me what is happening there at the end of the script $dir, but I'm guessing it is a call to run any executable script in any of the folders.

I did try but was not successful with some changes. Can you suggest a syntax that will work on FreeBSD?

**Comment by loz-hurst** [comment]
`run-parts` is part of the debianutils package (at least on debian and ubuntu).  I have not checked, but is may well be incompatible with RedHat derivatives (e.g. CentOS) if they do not provide a version?

On my non-Debian Linux box, this works:

```
/usr/bin/find $dir -executable -regex '.*/[A-Za-z0-9_-]+' -exec {} \;
```

I do not know if the `find` executable is in the same place on FreeBSD but Google suggests its installed.

**Comment by loz-hurst** [comment]
I've submitted a pull-request with a fix.

@lamixer if you are still around, could you test it on your FreeBSD system?  I've done it on a VirtualBox VM running FreeBSD but I have not used FreeBSD before so confirmation from a more experienced user would be appreciated!
