### ISSUE TITLE
Depend on the package providing run-parts

### ISSUE THREAD

**Issue by loz-hurst** [mythic-beasts/dehydrated-code-rack#4]
The debian control file for this tool does not currently depend on debianutils, which provides the `run-parts` tool.

Should it?  Or because debianutils is listed as 'essential', it this not necessary?  I'm not a Debian package maintainer - these are not rhetorical questions.

**Comment by simon--taylor** [comment]
This isn't necessary.

[Debian Policy section 3.5](https://www.debian.org/doc/debian-policy/ch-binary.html#dependencies)

> Packages are not required to declare any dependencies they have on other packages which are marked Essential (see below), and should not do so unless they depend on a particular version of that package.

**Comment by loz-hurst** [comment]
Thanks Simon, as I said, I'm not a Debian packager so wasn't sure.  Took me a bit of digging to figure out that run-parts was not available on any other distro, by searching the Debian package database for where it came from, which prompted the question.
